export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const ISAUTH_USER = "ISAUTH_USER";
export const ISAUTH_SUCCESS = "ISAUTH_SUCCESS";
export const ISAUTH_FAIL = "ISAUTH_FAIL";

export const GET_USER = "GET_USER";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";

export const LIST_SHIPPING_SUCCESS = "PRODUCT_SHIPPING_SUCCESS";
export const LIST_SHIPPING_REQUEST = "LIST_SHIPPING_REQUEST";
export const LIST_SHIPPING_FAIL = "LIST_SHIPPING_FAIL";

export const CART_LIST_CONFIRM = "CART_LIST_CONFIRM";

export const ORDER_LIST_ADMIN = "ORDER_LIST_ADMIN";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const ORDER_REMOVE_ADMIN_LIST = "ORDER_REMOVE_ADMIN_LIST";
export const SEARCH_ORDER = "SEARCH_ORDER";
